### ISSUE TITLE
0.1.0 release checklist

### ISSUE THREAD

**Issue by w4ll3** [spruceid/siwe-ruby#1]
Points to achieve parity with `siwe`

- [x] basic message fields
- [x] message generation
- [ ] message abnf parsing
- [ ] regex parsing (do we need this one?)
- [ ] message validation
- [ ] contract wallet util (might be a problem)
